Handle dynamic IAM secrets
exoscale/exoscale-cloud-controller-manager pull request #29
Opened 2021-01-29 10:34 UTC by 7fELF

Allows the Exoscale IAM secret to be loaded from a file, and automatically reloaded when this file is modified.

The configuration file is a JSON file that follows the format of the secret created by the [exoscale IAM vault plugin]h(ttps://github.com/exoscale/vault-plugin-secrets-exoscale)

Templating that file from vault ends up being as easy as:
```
{{- with secret "exoscale/apikey/my-ccm-role" -}}
{{ .Data | toJSON }}
{{- end }}
```

All call to egoscale are now guarded by a Mutex preventing its use while the IAM credential are being updated.

2021-01-29 15:49 UTC, falzm requested changes
Do you plan on testing this new scenario in the integration tests suite?

2021-01-29 15:49 UTC, falzm commented on exoscale/client.go
> +	infof("exoscale IAM credentials refreshed, now using %s (%s)", credentials.Name, credentials.APIKey)
```suggestion
	infof("Exoscale API credentials refreshed, now using %s (%s)", credentials.Name, credentials.APIKey)
```

2021-01-29 15:49 UTC, falzm commented on exoscale/client.go
> +			errorf("error while watching credentials file %q, %q", e.credentialsFile, err)
```suggestion
			errorf("error while watching credentials file %q: %v", e.credentialsFile, err)
```

2021-01-29 15:49 UTC, falzm commented on exoscale/client.go
> +		fatalf("failed to watch credentials file %q, %q", e.credentialsFile, err)
```suggestion
		fatalf("failed to watch credentials file %q: %v", e.credentialsFile, err)
```

2021-01-29 15:49 UTC, falzm commented on exoscale/client.go
> +func (e *exoscaleClient) GetVirtualMachine(ctx context.Context, uuid *egoscale.UUID) (*egoscale.VirtualMachine, error) {
I know that the underlying type is still `egoscale.VirtualMachine` for historical reasons (which will change in API v2), however we do our best to normalize the name everywhere as *[Compute] instance*:

```suggestion
func (e *exoscaleClient) GetInstance(ctx context.Context, uuid *egoscale.UUID) (*egoscale.VirtualMachine, error) {
```

2021-01-29 15:49 UTC, falzm commented on exoscale/client.go
> +				infof("refreshing IAM credential from file %s", e.credentialsFile)
```suggestion
				infof("refreshing API credentials from file %q", e.credentialsFile)
```

2021-01-29 15:49 UTC, falzm commented on exoscale/client.go
> +		infof("reading exoscale IAM credentials from environment")
```suggestion
		infof("reading Exoscale API credentials from environment")
```

2021-01-29 15:49 UTC, falzm commented on exoscale/client.go
>  		return nil, errors.New("incomplete or missing for API credentials")
Not changed in your PR, but it's a good opportunity to fix this typo :)

```suggestion
		return nil, errors.New("incomplete or missing Exoscale API credentials")
```

2021-01-29 15:49 UTC, falzm commented on exoscale/client.go
> +		infof("reading exoscale IAM credentials from file %q", exoclient.credentialsFile)
```suggestion
		infof("reading Exoscale API credentials from file %q", exoclient.credentialsFile)
```

2021-01-29 15:53 UTC, 7fELF commented on exoscale/common.go
> +	r, err := c.client.GetVirtualMachine(ctx, uuid)
```suggestion
	r, err := c.client.GetInstance(ctx, uuid)
```

2021-01-29 15:53 UTC, 7fELF commented on exoscale/loadbalancer.go
> +			instance, err := l.p.client.GetVirtualMachine(ctx, egoscale.MustParseUUID(node.Status.NodeInfo.SystemUUID))
```suggestion
			instance, err := l.p.client.GetInstance(ctx, egoscale.MustParseUUID(node.Status.NodeInfo.SystemUUID))
```

2021-02-01 09:24 UTC, exo-cedric approved these changes
lgtm, afaict. thx

2021-02-01 09:34 UTC, sgmac approved these changes

2021-02-01 10:21 UTC, pierre-emmanuelJ approved these changes

2021-02-04 08:19 UTC, falzm approved these changes
LGTM 👍

2021-02-04 08:21 UTC, merged